// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using limiredo_backend.Db;

#nullable disable

namespace limiredo_backend.Migrations
{
    [DbContext(typeof(LimiredoDbContext))]
    partial class LimiredoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("limiredo_backend.Db.Sound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("File")
                        .HasColumnType("longtext")
                        .HasColumnName("file");

                    b.Property<int>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<int>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.ToTable("sound");
                });
#pragma warning restore 612, 618
        }
    }
}
